# Generated by Django 3.2.5 on 2021-07-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_touring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touring',
            old_name='vinyl',
            new_name='artist',
        ),
        migrations.AlterField(
            model_name='touring',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
